from decimal import Decimal
from datetime import date



class Repository():
    #Aliases

    Integracion=[
       {'routine':'PGSSALDOSREP',
        'keyword':'saldos_diarios',
        'output':'table',
       'parameters':
                    [{'order':'1','name':'Tipo','type':str,'default':'G','required':False},
                     {'order':'2','name':'Instrumento','type':str,'default':"",'required':False},
                     {'order':'3','name':'OrigenID','type':'int','default':0,'required':False},                  
                     {'order':'4','name':'Consolidado','type':str,'default':'N', 'required':False },
                    ]
       },


       
       {'routine':'CLIENTESCON',
        'keyword':'cliente_detalle',
        'output':'table',
       'parameters':
                [   { 'order':'1','name':'ClienteID','type':str,'default':'0','required':True},
                    {'order':'2','name':'Instrumento','type':str, 'default':"",'required':False},
                    {'order':'3','name':'OrigenID','type':'int', 'default':"",'required':False},            
                    {'order':'4','name':'Consolidado','type':str,'default':1, 'required':False},
                    {'order':'5','name':'Consolidado','type':str,'default':1, 'required':False},
                    {'order':'6','name':'Consolidado','type':str,'default':1, 'required':False}, 
                    {'order':'7','name':'Consolidado','type':str,'default':'1900-01-01', 'required':False}, 
                    {'order':'8','name':'Consolidado','type':str,'default':"", 'required':False},
                    {'order':'9','name':'Consolidado','type':str,'default':"", 'required':False}, 
                    {'order':'10','name':'Consolidado','type':str,'default':1, 'required':False}, 
                    {'order':'11','name':'Consolidado','type':str,'default':0, 'required':False},
                ]
       },
        {'routine':'LINEASCREDITOALT',
        'keyword':'linea_credito',
        'output':'message',
       'parameters':
                [{'order':1,'name':'ClienteID','type':int,'default':'0','required':True},
                {'order':2,'name':'CuentaID','type':int, 'default':"",'required':True},
                {'order':3,'name':'MonedaID','type':int, 'default':1,'required':False},                                   
                {'order':4,'name':'SucursalID','type':int,'default':1, 'required':True},
                {'order':5,'name':'FolioContrato','type':str,'default':1, 'required':True},
                {'order':6,'name':'FechaInicio','type':str,'default':1, 'required':True},
                {'order':7,'name':'FechaVencimiento','type':str,'default':'1900-01-01', 'required':True},
                {'order':8,'name':'ProductoCreditoID','type':str,'default':"", 'required':True},
                {'order':9,'name':'Solicitado','type':Decimal,'default':0.0, 'required':True},
                {'order':10,'name':'PromotorID','type':int,'default':0, 'required':False},
                {'order':11,'name':'Proyecto','type':str,'default':"N", 'required':False},
                {'order':12,'name':'DestinoCreID','type':int,'default':"N", 'required':False},
                {'order':13,'name':'TasaMaxima','type':Decimal,'default':"N", 'required':False},
                {'order':14,'name':'Frecuencia','type':str,'default':"N", 'required':False},
                {'order':15,'name':'EsAgropecuario','type':str,'default':"N", 'required':False},
                {'order':16,'name':'TipoLineaAgroID','type':int,'default':0, 'required':False},
                {'order':17,'name':'ManejaComAdmon','type':str,'default':"N", 'required':False},
                {'order':18,'name':'ForCobComAdmon','type':str,'default':"", 'required':False},
                {'order':19,'name':'PorcentajeComAdmon','type':Decimal,'default':0.0, 'required':False},
                {'order':20,'name':'ManejoComGarantia','type':str,'default':"", 'required':False},
                {'order':21,'name':'ForCobComGarantia','type':str,'default':"", 'required':False},
                {'order':22,'name':'PorcentajeComGarantia','type':Decimal,'default':0.0, 'required':False},
                {'order':23,'name':'Salida','type':str,'default':"S", 'required':False},
                {'order':24,'name':'NumErr','type':int,'default':0, 'required':False},
                {'order':25,'name':'ErrMen','type':str,'default':"", 'required':False},
                {'order':26,'name':'EmpresaID','type':int,'default':0, 'required':False},
                {'order':27,'name':'Usuario','type':int,'default':0, 'required':False},
                {'order':28,'name':'FechaActual','type':str,'default':date.today(), 'required':False},
                {'order':29,'name':'DireccionIP','type':str,'default':"127.0.0.1", 'required':False},
                {'order':30,'name':'ProgramaID','type':str,'default':"", 'required':False},
                {'order':31,'name':'Sucursal','type':int,'default':0, 'required':False},
                {'order':32,'name':'NumTransaccion','type':int,'default':0, 'required':False},
                ]
        },
        {'routine':'AVALESALT',
        'keyword':'alta-aval',
        'output':'message',
       'parameters':
                [{'order':1,'name':'PrimerNom','type':str,'default':"",'required':True},
                {'order':2,'name':'SegundoNom','type':str, 'default':"",'required':False},
                {'order':3,'name':'TercerNom','type':str, 'default':"",'required':False},                                   
                {'order':4,'name':'ApellidoPat','type':str,'default':"", 'required':True},
                {'order':5,'name':'ApellidoMat','type':str,'default':"", 'required':True},
                {'order':6,'name':'Telefono','type':str,'default':"", 'required':False}, 
                {'order':7,'name':'Calle','type':str,'default':"", 'required':True},
                {'order':8,'name':'NumExterior','type':str,'default':"", 'required':True},
                {'order':9,'name':'NumInterior','type':str,'default':"", 'required':False},
                {'order':10,'name':'Manzana','type':str,'default':"", 'required':False},
                {'order':11,'name':'Lote','type':str,'default':"", 'required':False},
                {'order':12,'name':'Colonia','type':str,'default':"", 'required':True},
                {'order':13,'name':'LocalidadID','type':int,'default':0, 'required':True},
                {'order':14,'name':'ColoniaID','type':int,'default':0, 'required':True},
                {'order':15,'name':'MunicipioID','type':int,'default':0, 'required':True},
                {'order':16,'name':'EstadoID','type':int,'default':0, 'required':True},
                {'order':17,'name':'CP','type':str,'default':"", 'required':True},
                {'order':18,'name':'TipoPersona','type':str,'default':"", 'required':True},
                {'order':19,'name':'RazonSocial','type':str,'default':"", 'required':False},
                {'order':20,'name':'RFC','type':str,'default':"", 'required':True},
                {'order':21,'name':'Latitud','type':str,'default':"", 'required':False},
                {'order':22,'name':'Longitud','type':str,'default':"", 'required':False},
                {'order':23,'name':'FechaNac','type':str,'default':"1900-01-01", 'required':True},
                {'order':24,'name':'TelefonoCel','type':str,'default':"", 'required':True},
                {'order':25,'name':'RFCpm','type':str,'default':"", 'required':False},
                {'order':26,'name':'Sexo','type':str,'default':"", 'required':True},
                {'order':27,'name':'EstadoCivil','type':str,'default':"", 'required':True},
                {'order':28,'name':'ExtTelefonoPart','type':str,'default':"", 'required':False},
                {'order':29,'name':'Esc_Tipo','type':str,'default':"-1", 'required':False},
                {'order':30,'name':'NomApoder','type':str,'default':"", 'required':False},
                {'order':31,'name':'RFC_Apoder','type':str,'default':"", 'required':False},
                {'order':32,'name':'EscriPub','type':str,'default':"", 'required':False},
                {'order':33,'name':'LibroEscr','type':str,'default':"", 'required':False},
                {'order':34,'name':'VolumenEsc','type':str,'default':"", 'required':False},
                {'order':35,'name':'FechaEsc','type':str,'default':"1900-01-01", 'required':False},
                {'order':36,'name':'EstadoIDEsc','type':int,'default':0, 'required':False},
                {'order':37,'name':'LocalEsc','type':int,'default':0, 'required':False},
                {'order':38,'name':'Notaria','type':int,'default':0, 'required':False},
                {'order':39,'name':'DirecNotar','type':str,'default':"", 'required':False},
                {'order':40,'name':'NomNotario','type':str,'default':"", 'required':False},
                {'order':41,'name':'RegistroPub','type':str,'default':"", 'required':False},
                {'order':42,'name':'FolioRegPub','type':str,'default':"", 'required':False},
                {'order':43,'name':'VolRegPub','type':str,'default':"", 'required':False},
                {'order':44,'name':'LibroRegPub','type':str,'default':"", 'required':False},
                {'order':45,'name':'AuxiRegPub','type':str,'default':"", 'required':False},
                {'order':46,'name':'FechaRegPub','type':str,'default':"1900-01-01", 'required':False},
                {'order':47,'name':'EstadoIDReg','type':int,'default':0, 'required':False},
                {'order':48,'name':'LocalRegPub','type':int,'default':0, 'required':False},
                {'order':49,'name':'Nacion','type':str,'default':"N", 'required':False},
                {'order':50,'name':'LugarNacimiento','type':int,'default':int, 'required':True},
                {'order':51,'name':'OcupacionID','type':int,'default':0, 'required':True},
                {'order':52,'name':'Puesto','type':str,'default':"", 'required':False},
                {'order':53,'name':'DomicilioTrabajo','type':str,'default':"", 'required':False},
                {'order':54,'name':'TelefonoTrabajo','type':str,'default':"", 'required':False},
                {'order':55,'name':'ExtTelTrabajo','type':str,'default':"", 'required':False},
                {'order':56,'name':'NumIdentificacion','type':str,'default':"", 'required':False},
                {'order':57,'name':'FechaExpIdentif','type':str,'default':"1900-01-01", 'required':False},
                {'order':58,'name':'FechaVencIdentif','type':str,'default':"1900-01-01", 'required':False},
                {'order':59,'name':'Salida','type':str,'default':"S", 'required':False},
                {'order':60,'name':'NumErr','type':int,'default':0, 'required':False},
                {'order':61,'name':'ErrMen','type':str,'default':"", 'required':False},
                {'order':62,'name':'EmpresaID','type':int,'default':0, 'required':False},
                {'order':63,'name':'Usuario','type':int,'default':0, 'required':False},
                {'order':64,'name':'FechaActual','type':str,'default':date.today(), 'required':False},
                {'order':65,'name':'DireccionIP','type':str,'default':"127.0.0.1", 'required':False},
                {'order':66,'name':'ProgramaID','type':str,'default':"", 'required':False},
                {'order':67,'name':'Sucursal','type':int,'default':0, 'required':False},
                {'order':68,'name':'NumTransaccion','type':int,'default':0, 'required':False},
                ]
        },
        {'routine':'ASIGNAAVALESLINEASALT',
        'keyword':'asigna-aval',
        'output':'message',
       'parameters':
            [       {'order':'1','name':'LineaCreditoID','type':str,'default':'0','required':True},
                    {'order':2,'name':'AvalID','type':int, 'default':0,'required':False},
                    {'order':'3','name':'ClienteID','type':int, 'default':0,'required':False},
                    {'order':4,'name':'ProspectoID','type':int,'default':0, 'required':False},
                    {'order':'5','name':'Estatus','type':str,'default':1, 'required':False},
                    {'order':'6','name':'TipoRelacionID','type':str,'default':0, 'required':False},
                    {'order':'7','name':'TiempoDeConocido','type':str,'default':0, 'required':False}, 
                    {'order':'8','name':'Salida','type':str,'default':'S', 'required':False},
                    {'order':9,'name':'NumErr','type':int,'default':0, 'required':False},
                    {'order':'10','name':'ErrMen','type':str,'default':"", 'required':False},
                    {'order':'11','name':'EmpresaID','type':str,'default':1, 'required':False},
                    {'order':'12','name':'Usuario','type':str,'default':0, 'required':False},
                    {  'order':13,'name':'FechaActual','type':str,'default':'1900-01-01','required':False},               
                    {  'order':14,'name':'IP','type':str,'default':'127.0.0.1','required':False},
                    {  'order':15,'name':'ProgramaID','type':str,'default':'API','required':False},
                    {  'order':16,'name':'Sucursal','type':int,'default':1,'required':False},
                    {  'order':17,'name':'Transaccion','type':int,'default':1,'required':False},
                ]
       },



    ] # Integracion
    

    
    Cartera =[
            {'routine':'PGSVENCIMIENTOSREP',
            'keyword':'vencimientos',
            'output':'table',
            'parameters':[{  'order':1, 'name':'FechaInicio', 'type': str, 'default':'1900-01-01', 'required':True },
                        {  'order':2, 'name':'FechaFin', 'type':str, 'default':'1900-01-01', 'required':True },
                        {  'order': 3, 'name':'SucursalID', 'type':int, 'default':0, 'required':False },
                        {  'order': 4, 'name':'Moneda', 'type':int, 'default':0, 'required':False },
                        {  'order': 5, 'name':'ProductoID', 'type':int, 'default':0, 'required':False },
                        {  'order':6, 'name':'PromotorID', 'type':int, 'default':0, 'required':False },
                        {  'order':7, 'name':'Genero', 'type':str, 'default':"", 'required':False },
                        {  'order':8, 'name':'EstadoID', 'type':int, 'default':0, 'required':False },
                        {  'order':9, 'name':'MunicipioID', 'type':int, 'default':0, 'required':False },
                        {  'order':10, 'name':'MinDiasAtraso', 'type':int, 'default':0, 'required':False },
                        {  'order':11, 'name':'MaxDiasAtraso', 'type':int, 'default':99999, 'required':False },
                        {  'order':12, 'name':'InstNominaID', 'type':int, 'default':0, 'required':False },
                        {  'order':13, 'name':'ConvenioID', 'type':int, 'default':0, 'required':False },
                        {  'order':14, 'name':'EmpresaID', 'type':int, 'default':1, 'required':False },
                        {  'order':15, 'name':'Usuario', 'type':int, 'default':1, 'required':False },
                        {  'order':16, 'name':'FechaActual', 'type':str, 'default':'1900-01-01', 'required':False }, 
                        {  'order':17, 'name':'DireccionIP', 'type':str, 'default':'127.0.01', 'required':False },
                        {  'order':18, 'name':'ProgramaID', 'type':str, 'default':1, 'required':False },
                        {  'order':19, 'name':'Sucursal', 'type':int, 'default':1, 'required':False },                
                        {  'order':20, 'name':'Transaccion', 'type':int, 'default':1, 'required':False },]
            }
            ]
    Bulk =[
            {'routine':'PAGOCREDITOPRO',
            'keyword':'pago-credito',
            'output':'table',
            'parameters':[{  'order':1, 'name':'CreditoID', 'type': int, 'default':0, 'required':True },
                        {  'order':2, 'name':'CuentaID', 'type':int, 'default':0, 'required':True },
                        {  'order': 3, 'name':'MontoPagar', 'type':Decimal, 'default':0, 'required':True },
                        {  'order': 4, 'name':'MonedaID', 'type':int, 'default':1,   'required':False },
                        {  'order': 5, 'name':'EsPrepago', 'type':str, 'default':'N','required':False },
                        {  'order':6, 'name':'EsFiniquito', 'type':str, 'default':'N','required':False },
                        {  'order':7, 'name':'EmpresaID', 'type':int, 'default':1,'required':False },
                        {  'order':8, 'name':'Salida', 'type':str, 'default':'S', 'required':False },
                        {  'order':9, 'name':'MaestroPoliza', 'type':str, 'default':'S', 'required':False },
                        {  'order':10, 'name':'MontoPagado', 'type':Decimal, 'default':0, 'required':False},
                        {  'order':11, 'name':'@PolizaID', 'type':int, 'default':1, 'required':False },
                        {  'order':12, 'name':'@NumErr', 'type':int, 'default':0, 'required':False },
                        {  'order':13, 'name':'@ErrMen', 'type':int, 'default':0, 'required':False },
                        {  'order':14, 'name':'@Consecutivo', 'type':int, 'default':1, 'required':False },
                        {  'order':15, 'name':'ModoPago', 'type':str, 'default':'E', 'required':False },
                        {  'order':16, 'name':'Origen', 'type':str, 'default':'', 'required':False }, 
                        {  'order':17, 'name':'RespaldaCred', 'type':str, 'default':'S', 'required':False },
                        {  'order':18, 'name':'Usuario', 'type':int, 'default':1, 'required':False },
                        {  'order':19, 'name':'FechaActual', 'type':str, 'default':'1900-01-01', 'required':False },            
                        {  'order':20, 'name':'IP', 'type':str, 'default':'127.0.0.1', 'required':False },
                        {  'order':21, 'name':'ProgramaID', 'type':str, 'default':'API', 'required':False },
                        {  'order':22, 'name':'Sucursal', 'type':int, 'default':1, 'required':False },
                        {  'order':23, 'name':'Transaccion', 'type':int, 'default':1, 'required':False },
                    ]
            },
            {'routine':'CARGOABONOCTAPRO',
            'keyword':'deposito',
            'output':'message',
            'parameters':[{  'order':1, 'name':'CuentaAhoID', 'type': int, 'default':0, 'required':True },
                        {  'order':2, 'name':'ClienteID', 'type':int, 'default':0, 'required':True },
                        {  'order': 3, 'name':'NumeroMov', 'type':Decimal, 'default':1, 'required':True },
                        {  'order': 4, 'name':'Fecha', 'type':str, 'default':'1900-01-01',   'required':False },
                        {  'order': 5, 'name':'FechaAplicacion', 'type':str, 'default':'1900-01-01','required':False },
                        {  'order':6, 'name':'NatMovimiento', 'type':str, 'default':'A','required':False },
                        {  'order':7, 'name':'CantidadMov', 'type':int, 'default':0,'required':False },
                        {  'order':8, 'name':'DescripcionMov', 'type':str, 'default':'DESPOSITO DE EFECTIVO', 'required':False },
                        {  'order':9, 'name':'ReferenciaMov', 'type':str, 'default':'00000000', 'required':False },
                        {  'order':10, 'name':'TipoMovAhoID', 'type':Decimal, 'default':28, 'required':False},
                        {  'order':11, 'name':'MonedaID', 'type':int, 'default':1, 'required':False },
                        {  'order':12, 'name':'SucCliente', 'type':int, 'default':1, 'required':False },
                        {  'order':13, 'name':'AltaEncPoliza', 'type':int, 'default':'S', 'required':False },
                        {  'order':14, 'name':'ConceptoCon', 'type':int, 'default':1, 'required':False },
                        {  'order':15, 'name':'Poliza', 'type':str, 'default':0, 'required':False },
                        {  'order':16, 'name':'AltaPoliza', 'type':str, 'default':'S', 'required':False }, 
                        {  'order':17, 'name':'ConceptoAho', 'type':str, 'default':1, 'required':False },
                        {  'order':18, 'name':'NatConta', 'type':int, 'default':'C', 'required':False },
                        {  'order':19, 'name':'Salida', 'type':str, 'default':'S', 'required':False },            
                        {  'order':20, 'name':'NumErr', 'type':str, 'default':0, 'required':False },
                        {  'order':21, 'name':'ErrMen', 'type':str, 'default':"", 'required':False },
                        {  'order':22, 'name':'Consecutivo', 'type':int, 'default':1, 'required':False },
                        {  'order':23, 'name':'EmpresaID', 'type':int, 'default':1, 'required':False },
                        {  'order':23, 'name':'Usuario', 'type':int, 'default':1, 'required':False },
                        {  'order':23, 'name':'FechaActual', 'type':int, 'default':'1900-01-01', 'required':False },
                        {  'order':23, 'name':'DireccionIP', 'type':int, 'default':'127.0.01', 'required':False },
                        {  'order':23, 'name':'ProgramaID', 'type':int, 'default':1, 'required':False },
                        {  'order':23, 'name':'Sucursal', 'type':int, 'default':1, 'required':False },
                        {  'order':23, 'name':'NumTransaccion', 'type':int, 'default':1, 'required':False },
                    ]
            },
            ]

    Catalogos = [
         { 'routine':'TIPORELACIONESLIS',
            'keyword':'tipo-relaciones',
            'output':'table',
            'parameters':[{'order':'1', 'name':'TipoRelacion', 'type':int, 'default':0, 'required':False },
                        {'order':'2','name':'Descripcion','type':str,'default':"",'required':False },
                        {'order':'3','name':'NumList','type':'int','default':2,'required':False},
                        {  'order':14, 'name':'EmpresaID', 'type':int, 'default':1, 'required':False },
                        {  'order':15, 'name':'Usuario', 'type':int, 'default':1, 'required':False },
                        {  'order':16, 'name':'FechaActual', 'type':str, 'default':'1900-01-01', 'required':False },
                        {  'order':17, 'name':'DireccionIP', 'type':str, 'default':'127.0.01', 'required':False },
                        {  'order':18, 'name':'ProgramaID', 'type':str, 'default':1, 'required':False },
                        {  'order':19, 'name':'Sucursal', 'type':int, 'default':1, 'required':False },                
                        {  'order':20, 'name':'Transaccion', 'type':int, 'default':1, 'required':False },
                        ]
        },
        { 'routine':'DESTINOSCREDITOLIS',
            'keyword':'destinos-credito',
            'output':'table',
            'parameters':[{'order':'1', 'name':'DestinoCredito', 'type':str, 'default':"", 'required':False },
                        {'order':'2','name':'ProducCreditoID','type':int,'default':0,'required':False },
                        {'order':'3','name':'NumList','type':'int','default':1,'required':False},
                        {  'order':14, 'name':'EmpresaID', 'type':int, 'default':1, 'required':False },
                        {  'order':15, 'name':'Usuario', 'type':int, 'default':1, 'required':False },
                        {  'order':16, 'name':'FechaActual', 'type':str, 'default':'1900-01-01', 'required':False },
                        {  'order':17, 'name':'DireccionIP', 'type':str, 'default':'127.0.01', 'required':False },
                        {  'order':18, 'name':'ProgramaID', 'type':str, 'default':1, 'required':False },
                        {  'order':19, 'name':'Sucursal', 'type':int, 'default':1, 'required':False },                
                        {  'order':20, 'name':'Transaccion', 'type':int, 'default':1, 'required':False },
                        ]
        },
         { 'routine':'PRODUCTOSCREDITOLIS',
            'keyword':'productos-credito',
            'output':'table',
            'parameters':[{'order':'1', 'name':'Descripcion', 'type':str, 'default':"", 'required':False },
                        {'order':'2','name':'NumList','type':int,'default':0,'required':False },
                        {  'order':14, 'name':'EmpresaID', 'type':int, 'default':1, 'required':False },
                        {  'order':15, 'name':'Usuario', 'type':int, 'default':1, 'required':False },
                        {  'order':16, 'name':'FechaActual', 'type':str, 'default':'1900-01-01', 'required':False },
                        {  'order':17, 'name':'DireccionIP', 'type':str, 'default':'127.0.01', 'required':False },
                        {  'order':18, 'name':'ProgramaID', 'type':str, 'default':1, 'required':False },
                        {  'order':19, 'name':'Sucursal', 'type':int, 'default':1, 'required':False },                
                        {  'order':20, 'name':'Transaccion', 'type':int, 'default':1, 'required':False },
                        ]
        },
        { 'routine':'PROMOTORESLIS',
            'keyword':'promotores-credito',
            'output':'table',
            'parameters':[{'order':'1', 'name':'NombPromot', 'type':str, 'default':"", 'required':False },
            {'order':'2','name':'SucursalID','type':int,'default':0,'required':False },
            {'order':'3','name':'NumLis','type':int,'default':4,'required':False }, # promotor scursal
            {  'order':14, 'name':'EmpresaID', 'type':int, 'default':1, 'required':False },
            {  'order':15, 'name':'Usuario', 'type':int, 'default':1, 'required':False },
            {  'order':16, 'name':'FechaActual', 'type':str, 'default':'1900-01-01', 'required':False },
            {  'order':17, 'name':'DireccionIP', 'type':str, 'default':'127.0.01', 'required':False },
            {  'order':18, 'name':'ProgramaID', 'type':str, 'default':1, 'required':False },
            {  'order':19, 'name':'Sucursal', 'type':int, 'default':1, 'required':False },                
            {  'order':20, 'name':'Transaccion', 'type':int, 'default':1, 'required':False },
                        ]
        },
        { 'routine':'SUCURSALESLIS',
            'keyword':'sucursales',
            'output':'table',
            'parameters':[{'order':1,'name':'NombreSucur','type':str,'default':"",'required':False },
                        {'order':2,'name':  'NumLis','type':int,'default':4, 'required':False },
                        {'order':3,'name':  'EmpresaID','type':int,'default':1,'required':False },
                        {'order':4,'name':  'Usuario','type':int,'default':1,'required':False },
                        {'order':5,'name':  'FechaActual','type':str,'default':'1900-01-01','required':False },
                        {'order':6,'name':  'DireccionIP','type':str,'default':'127.0.01','required':False },
                        {'order':7,'name':  'ProgramaID','type':str,'default':1,'required':False},
                        {'order':8,'name':  'Sucursal','type':int,'default':1,'required':False },                
                        {'order':9,'name':  'Transaccion','type':int,'default':1,'required':False },
                        ]
        },
        




       
                ]

